-- Parcel Hub: initial application schema
--
-- Passwords are managed only by Supabase Auth. This public schema intentionally
-- contains no provider OAuth tokens, IMAP/SMTP app passwords, raw email content,
-- message headers, attachments, or raw provider message IDs.

create table public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_is_trimmed
    check (
      display_name is null
      or (
        char_length(display_name) between 1 and 60
        and display_name = btrim(display_name)
      )
    )
);

create table public.mail_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  provider text not null,
  status text not null default 'disconnected',
  last_synced_at timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mail_connections_provider_valid
    check (provider in ('gmail', 'naver')),
  constraint mail_connections_status_valid
    check (status in ('disconnected', 'connected', 'syncing', 'needs_reauth', 'error')),
  constraint mail_connections_error_code_valid
    check (
      last_error_code is null
      or last_error_code in (
        'authorization_failed',
        'connection_failed',
        'provider_unavailable',
        'rate_limited',
        'reauth_required'
      )
    ),
  constraint mail_connections_one_per_provider unique (user_id, provider),
  constraint mail_connections_id_user_unique unique (id, user_id)
);

create table public.mail_imports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  connection_id uuid,
  source_kind text not null,
  -- SHA-256 fingerprint generated by a trusted server from a provider message ID
  -- or submitted iPhone Shortcut payload. Never store the raw identifier/body.
  source_fingerprint text not null,
  status text not null default 'processed',
  source_received_at timestamptz,
  parcel_count integer not null default 0,
  created_at timestamptz not null default now(),
  constraint mail_imports_source_kind_valid
    check (source_kind in ('gmail', 'naver', 'iphone_shortcut', 'manual')),
  constraint mail_imports_status_valid
    check (status in ('queued', 'processed', 'skipped', 'failed')),
  constraint mail_imports_fingerprint_valid
    check (source_fingerprint ~ '^[a-f0-9]{64}$'),
  constraint mail_imports_parcel_count_valid
    check (parcel_count between 0 and 100),
  constraint mail_imports_connection_matches_source
    check (
      (source_kind in ('gmail', 'naver') and connection_id is not null)
      or (source_kind in ('iphone_shortcut', 'manual') and connection_id is null)
    ),
  constraint mail_imports_id_user_unique unique (id, user_id),
  constraint mail_imports_deduplicate_source unique (user_id, source_kind, source_fingerprint),
  constraint mail_imports_connection_owner
    foreign key (connection_id, user_id)
    references public.mail_connections (id, user_id)
    on delete restrict
);

create table public.parcels (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  tracking_number text not null,
  carrier_code text not null default 'unknown',
  carrier_origin text not null default 'manual',
  management_status text not null default 'needs_check',
  memo text,
  source_import_id uuid,
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint parcels_tracking_number_valid
    check (
      char_length(tracking_number) between 6 and 64
      and tracking_number = btrim(tracking_number)
    ),
  constraint parcels_carrier_code_valid
    check (carrier_code ~ '^[a-z0-9][a-z0-9_-]{0,30}$'),
  constraint parcels_carrier_origin_valid
    check (carrier_origin in ('manual', 'context', 'format', 'imported')),
  constraint parcels_management_status_valid
    check (management_status in ('needs_check', 'received')),
  constraint parcels_memo_valid
    check (memo is null or char_length(memo) <= 240),
  constraint parcels_one_tracking_number_per_user unique (user_id, tracking_number),
  constraint parcels_import_owner
    foreign key (source_import_id, user_id)
    references public.mail_imports (id, user_id)
    on delete restrict
);

comment on table public.mail_connections is
  'Status-only record for an inbox integration. Credentials and tokens belong in server-only secrets or an encrypted vault, never this table.';
comment on table public.mail_imports is
  'Minimal import provenance only. Raw email/SMS content and provider message IDs must not be stored here.';

create index parcels_user_id_created_at_idx
  on public.parcels (user_id, created_at desc);
create index mail_imports_user_id_created_at_idx
  on public.mail_imports (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.parcels enable row level security;
alter table public.mail_connections enable row level security;
alter table public.mail_imports enable row level security;

-- The browser can never access data as anon. Authenticated users get only the
-- minimum table privileges required by the UI; mailbox connection/import writes
-- must happen in a server-side integration function.
revoke all on table public.profiles, public.parcels, public.mail_connections, public.mail_imports from anon;

grant select, update on table public.profiles to authenticated;
grant select, insert, update, delete on table public.parcels to authenticated;
grant select on table public.mail_connections, public.mail_imports to authenticated;
grant all on table public.profiles, public.parcels, public.mail_connections, public.mail_imports to service_role;

create policy "profiles_select_own"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "parcels_select_own"
  on public.parcels
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "parcels_insert_own"
  on public.parcels
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "parcels_update_own"
  on public.parcels
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "parcels_delete_own"
  on public.parcels
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "mail_connections_select_own"
  on public.mail_connections
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "mail_imports_select_own"
  on public.mail_imports
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

create trigger parcels_set_updated_at
  before update on public.parcels
  for each row execute function public.set_updated_at();

create trigger mail_connections_set_updated_at
  before update on public.mail_connections
  for each row execute function public.set_updated_at();

-- The signup trigger creates only an empty, non-authoritative profile row.
-- It intentionally does not trust user metadata for roles or authorization.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;
grant usage on schema public to supabase_auth_admin;
grant execute on function public.handle_new_user() to supabase_auth_admin;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
